# Numpy Cheatsheet
Copyright 2021 [Compass Mentis IT Limited](https://www.compassmentis.com).\
May be freely distributed under [Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/).

# Set up

In [1]:
import numpy as np

## Creating numpy arrays

In [2]:
# Function to show an array
def print_array(array):
    print(f'Shape: {array.shape}, Dimensions: {array.ndim}')
    print(array)    

In [3]:
# 0-D array (single value)
array = np.array(50)
print_array(array)

Shape: (), Dimensions: 0
50


In [4]:
# 1D array (list)
array = np.array([1, 2, 3])
print_array(array)

Shape: (3,), Dimensions: 1
[1 2 3]


In [5]:
# 2D array (grid)
array = np.array([[1, 2], [3, 4]])
print_array(array)

Shape: (2, 2), Dimensions: 2
[[1 2]
 [3 4]]


## Creating special types of numpy arrays

In [6]:
# A range of numbers, from start to end
array = np.arange(1, 10)
print_array(array)

Shape: (9,), Dimensions: 1
[1 2 3 4 5 6 7 8 9]


In [7]:
# A range of numbers, from start to end, every other number
array = np.arange(1, 10, 2)
print_array(array)

Shape: (5,), Dimensions: 1
[1 3 5 7 9]


In [8]:
# All zeros
array = np.zeros([2, 3])
print_array(array)

Shape: (2, 3), Dimensions: 2
[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# All ones
array = np.ones([2, 3])
print_array(array)

Shape: (2, 3), Dimensions: 2
[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
# Identity array of size (n x n)
array = np.eye(4)
print_array(array)

Shape: (4, 4), Dimensions: 2
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# A list of evenly spaced numbers
array = np.linspace(1, 10, 21)
print_array(array)

Shape: (21,), Dimensions: 1
[ 1.    1.45  1.9   2.35  2.8   3.25  3.7   4.15  4.6   5.05  5.5   5.95
  6.4   6.85  7.3   7.75  8.2   8.65  9.1   9.55 10.  ]


In [12]:
# Random numbers, uniformly distributed
array = np.random.uniform(0, 10, 15)
print_array(array)

Shape: (15,), Dimensions: 1
[7.84783605 3.27179337 3.91457958 2.35582865 1.79143727 6.2520994
 9.71885936 5.77344675 6.22874345 4.46208119 1.14012131 6.30157507
 3.25053242 1.01263872 3.98373773]


## Accessing array elements

In [13]:
# Create an array
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array[0], '\t(1st sub-array along 1st dimension)')
print(array[1], '\t(2nd sub-array along 1st dimension)')
print(array[0][0], '\t\t(1st element of 1st sub-array along 1st dimension)')
print(array[0, 0], '\t\t(1st element of 1st sub-array along 1st dimension, again)')
print(array[:, 0], '\t\t(1st element of both sub-arrays, along 2nd dimension)')
print(array[:, 1], '\t\t(2nd element of both sub-arrays, along 2nd dimension)')
print(array[:, 2], '\t\t(3rd element of both sub-arrays, along 2nd dimension)')

[1 2 3] 	(1st sub-array along 1st dimension)
[4 5 6] 	(2nd sub-array along 1st dimension)
1 		(1st element of 1st sub-array along 1st dimension)
1 		(1st element of 1st sub-array along 1st dimension, again)
[1 4] 		(1st element of both sub-arrays, along 2nd dimension)
[2 5] 		(2nd element of both sub-arrays, along 2nd dimension)
[3 6] 		(3rd element of both sub-arrays, along 2nd dimension)


## Data types

In [14]:
# Show the data type
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [15]:
# Create an array for a given data type
arr = np.array([1, 2, 3, 4], dtype=np.int8)
print(arr.dtype)

int8


### Common numerical data types
* .int8, .int16, .int32, .int64 - signed integers, 8/16/32/64 bits
* .uint8, .uint16, .uint32, .uint64 - unsigned integer, 8/16/32/64 bits
* .float32, .float64 - float, 32/64 bits

## Simple array calculations

In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print('array\n', array, '\n')
print('array + array\n', array + array, '\n')
print('array - array\n', array - array, '\n')
print('array + 1\n', array + 1, '\n')
print('array + [1, 2, 3]\n', array + [1, 2, 3], '\n')
print('array + [[1], [2]]\n', array + [[1], [2]], '\n')
print('array * 3\n', array * 3, '\n')
print('3 * array\n', 3 * array, '\n')
print('array * array\n', array * array, '\n')
print('array ** 2 (squared)\n', array ** 2, '\n')
print('array * [1, 2, 3]\n', array * [1, 2, 3], '\n')
print('array * [[1], [2]]\n', array * [[1], [2]], '\n')

array
 [[1 2 3]
 [4 5 6]] 

array + array
 [[ 2  4  6]
 [ 8 10 12]] 

array - array
 [[0 0 0]
 [0 0 0]] 

array + 1
 [[2 3 4]
 [5 6 7]] 

array + [1, 2, 3]
 [[2 4 6]
 [5 7 9]] 

array + [[1], [2]]
 [[2 3 4]
 [6 7 8]] 

array * 3
 [[ 3  6  9]
 [12 15 18]] 

3 * array
 [[ 3  6  9]
 [12 15 18]] 

array * array
 [[ 1  4  9]
 [16 25 36]] 

array ** 2 (squared)
 [[ 1  4  9]
 [16 25 36]] 

array * [1, 2, 3]
 [[ 1  4  9]
 [ 4 10 18]] 

array * [[1], [2]]
 [[ 1  2  3]
 [ 8 10 12]] 



## Changing the shape of an array

In [17]:
# From 1D, 1 row of 15 numbers
# To 2D, 3 rows of 5 numbers
array = np.random.uniform(0, 10, 15)
array = array.reshape(3, 5)
print_array(array)

Shape: (3, 5), Dimensions: 2
[[4.67819469 6.82899959 2.57390633 7.74238093 3.19947234]
 [9.45306513 9.44641973 2.34338799 1.17596341 0.26884698]
 [0.73363389 3.32749279 8.35641364 5.31181959 7.0002694 ]]


In [18]:
# As above, using a wild card (-1)
# From 1D, 1 row of 15 numbers
# To 2D, 3 rows of 5 numbers
array = np.random.uniform(0, 10, 15)
array = array.reshape(3, -1)
print_array(array)

Shape: (3, 5), Dimensions: 2
[[0.15414579 2.87289737 2.4910165  3.15651683 3.67534587]
 [2.92694424 4.44759413 1.38110096 7.17754738 7.32141636]
 [2.50620614 5.16554941 1.48761785 6.32300609 5.50811934]]


## Simple statistics

In [19]:
# Set up - create a random array

# Make sure random array is same everytime this is run
np.random.seed(10)
array = np.random.uniform(-10, 10, 25)
print_array(array)

Shape: (25,), Dimensions: 1
[ 5.42641287 -9.58496101  2.6729647   4.97607765 -0.02985975 -5.50406709
 -6.0387427   5.21061424 -6.61778327 -8.23320372  3.70719637  9.06786692
 -9.92103467  0.24384527  6.25241923  2.25052134  4.43510635 -4.16247864
  8.35548245  4.29151567  0.85088736 -7.15659905 -2.5331848   3.4826723
 -1.16333651]


In [20]:
print('Minimum', array.min(), ' which is at index', array.argmin())
print('Maximum', array.max(), ' which is at index', array.argmax())
print('Mean', array.mean())
print('Total', array.sum())
print('Number of items', len(array))

Minimum -9.92103467344171  which is at index 12
Maximum 9.06786692389873  which is at index 11
Mean 0.011133260035354624
Total 0.2783315008838656
Number of items 25


## Advanced aggregate functions

In [21]:
# Set up - creating a random 2 x 3 array
np.random.seed(10)
array = np.random.randint(0, 10, 9).reshape(3, 3)
print_array(array)

Shape: (3, 3), Dimensions: 2
[[9 4 0]
 [1 9 0]
 [1 8 9]]


In [22]:
# Sum on axis 0 - total of each column
array.sum(axis=0)

array([11, 21,  9])

In [23]:
# Sum on axis 1 - total of each row
array.sum(axis=1)

array([13, 10, 18])