# Built-In Math Module and the Numpy Package

* Math Module
 * Math Module Docs: https://docs.python.org/3/library/math.html
 * Math Module Tutorial: https://www.w3schools.com/python/module_math.asp
* Numpy Package
 * NumPy the absolute basics for beginners: https://numpy.org/doc/stable/user/absolute_beginners.html
 * NumPy Docs: https://numpy.org/doc/stable/
 * NumPy quickstart: https://numpy.org/doc/stable/user/quickstart.html

In [1]:
import math
print(math.sqrt(25))           # 5.0
print(math.pi)                 # pi = 3.141592653589793
print(math.cos(math.pi/3))     # pi/3 radians = 60 degrees so cosine is 0.5 ~= 0.5000000000000001
print(math.cos(math.pi/2))     # pi/2 radians = 90 degrees so cosine is 0.0 ~= 6.123233995736766e-17
print(math.sin(math.pi/2))     # pi/2 radians = 90 degrees so sine is 1.0
print(math.degrees(2*math.pi)) # 2*pi radians = 360 degrees
print(math.radians(180))       # 180 degrees = pi radians = 3.141592653589793
print(math.e)                  # 2.718281828459045
print(2**3)                    # 8
print(math.pow(2, 3))          # 8.0
print(25**0.5)                 # 5.0
print(math.pow(25, 0.5))       # 5.0
print(math.log(math.e**4))     # 4
print(math.log(1000, 10))      # 3 ~= 2.9999999999999996
print(math.log(32, 2))         # 5.0
print(math.gcd(32, 84))        # 4
print(math.factorial(5))       # 120
print(math.inf)                # inf
print(math.nan)                # nan

5.0
3.141592653589793
0.5000000000000001
6.123233995736766e-17
1.0
360.0
3.141592653589793
2.718281828459045
8
8.0
5.0
5.0
4.0
2.9999999999999996
5.0
4
120
inf
nan


In [5]:
# Based on: https://www.tutorialspoint.com/numpy/numpy_determinant.htm
# Calculate the detreminant of a matrix

import numpy as np

matrix = np.array([[1,2], [3,4]])
print (matrix)
print (np.linalg.det(matrix))
print ()
matrix = np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 
print (matrix)
print (np.linalg.det(matrix))

[[1 2]
 [3 4]]
-2.0000000000000004

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
-306.0


## Try It Out: Experiment on your own using various math module and numpy functions

- Review the documentation on several math module and numpy functions
- Try writing your own code examples using various math module and numpy functions to explore how they work
- Discuss with other students what you have discovered in your experiments on using math module and numpy functions